// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 DetailT.glb --transform -d
// Files: DetailT.glb [2.58MB] > C:\Users\andre\Downloads\DetailT-transformed.glb [2.51MB] (3%)
// */

import { useEffect, useMemo, useState } from "react";

import * as THREE from "three";
import { useTexture } from "@react-three/drei";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";

import { convertMaterialsToMeshBasicMaterial } from "../utils/convertMaterial";
import { useModalStore } from "../stores/modalStore";

import About from "../../components/About/About";
import Project from "../../components/Project/Project";
import UserManual from "../../components/UserManual/UserManual";
import RandomLinks from "../../components/RandomLinks/RandomLinks";
import Bookshelf from "../../components/Bookshelf/Bookshelf";

// The visitor climbs the interior atrium, so content is distributed across the
// interior back wall of each floor and faces the rising camera (+z): the ground
// floor introduces (about + manual), the middle floor shows the four projects,
// and the top floor carries the links + reading list. Each item is a
// self-contained framed panel — a dark matte with the image aspect-fitted on
// top, plus an invisible click-zone. The old single-room baked meshes
// (furniture + frames) are not rendered; the interior is the brick atrium plus
// these panels.

// Interior back-wall depth (world z, just in front of each storey's back wall,
// facing the camera) and eye-height per floor. Tuned against the dev server.
const WALL_Z = { ground: -4.4, middle: -3.6, top: -2.8 };
const FLOOR_Y = { ground: 67.5, middle: 73.0, top: 78.4 };

const aboutFrames = {
  about: { title: "About me", render: () => <About /> },
  manual: { title: "User Manual", render: () => <UserManual /> },
  links: { title: "Random Links", render: () => <RandomLinks /> },
  books: { title: "Currently Reading", render: () => <Bookshelf /> },
};

const projectNames = {
  one: "Multiplayer AI Agent Canvas",
  two: "matrixportfolio",
  three: "coding-monkey",
  four: "AI Native Sims City",
};

// Every framed panel, placed on its floor's interior back wall. `x` spreads the
// panels along the wall, centred near the camera column (world x -5.5).
const FRAMES = [
  { id: "about", kind: "about", floor: "ground", x: -8.0, img: "/images/me.webp" },
  { id: "manual", kind: "about", floor: "ground", x: -3.0, img: "/images/about-robot.webp" },
  { id: "one", kind: "project", floor: "middle", x: -9.6, img: "/images/agent-canvas.webp" },
  { id: "two", kind: "project", floor: "middle", x: -6.7, img: "/images/matrixportfolio.webp" },
  { id: "three", kind: "project", floor: "middle", x: -3.8, img: "/images/coding-monkey.webp" },
  { id: "four", kind: "project", floor: "middle", x: -0.9, img: "/images/ai-native-city.webp" },
  { id: "links", kind: "about", floor: "top", x: -7.5, img: "/images/newsletter.webp" },
  { id: "books", kind: "about", floor: "top", x: -3.5, img: "/images/books.webp" },
];

const PANEL = { matte: [2.0, 1.5], photo: [1.7, 1.2], click: [2.0, 1.5] };
const ABOUT_MATTE = "#1c130b";
const PROJECT_MATTE = "#0d0d10";

const prepOverlayTexture = (texture) => {
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.center.set(0.5, 0.5);
  texture.offset.set(0, 0);
  texture.repeat.set(1, 1);
  texture.needsUpdate = true;
};

// Fit an image fully inside a box (contain), preserving aspect ratio.
const containSize = (texture, boxW, boxH) => {
  const img = texture && texture.image;
  const aspect = img && img.height ? img.width / img.height : 1;
  let w = boxW;
  let h = boxW / aspect;
  if (h > boxH) {
    h = boxH;
    w = boxH * aspect;
  }
  return [w, h];
};

export default function Model({ scrollProgress, ...props }) {
  // The GLB still loads (its materials warm the loader cache), but the old baked
  // interior meshes are no longer rendered.
  const { materials } = useGLTFWithKTX2("/models/DetailT-v1.glb");
  const [hoveredFrame, setHoveredFrame] = useState(null);
  const { openModal } = useModalStore();

  useMemo(() => convertMaterialsToMeshBasicMaterial(materials, 0), [materials]);

  const srcByID = useMemo(
    () => Object.fromEntries(FRAMES.map((f) => [f.id, f.img])),
    []
  );
  const textures = useTexture(srcByID, (loaded) => {
    Object.values(loaded).forEach(prepOverlayTexture);
  });

  const handleClick = (frame) => {
    if (frame.kind === "about") {
      const modal = aboutFrames[frame.id];
      openModal(modal.title, modal.render(), frame.id);
    } else {
      openModal(
        projectNames[frame.id],
        <Project projectID={frame.id} />,
        frame.id
      );
    }
  };

  useEffect(() => {
    document.body.style.cursor = hoveredFrame ? "pointer" : "auto";
  }, [hoveredFrame]);

  return (
    <group {...props} dispose={null}>
      {FRAMES.map((frame) => {
        const y = FLOOR_Y[frame.floor];
        const z = WALL_Z[frame.floor];
        const matteColor = frame.kind === "project" ? PROJECT_MATTE : ABOUT_MATTE;
        const [mw, mh] = PANEL.matte;
        const [iw, ih] = containSize(
          textures[frame.id],
          PANEL.photo[0],
          PANEL.photo[1]
        );
        const hovered = hoveredFrame === frame.id;
        return (
          <group key={frame.id} position={[frame.x, y, z]}>
            <mesh position={[0, 0, -0.01]} raycast={() => null}>
              <planeGeometry args={[mw, mh]} />
              <meshBasicMaterial
                color={hovered ? "#3a2a18" : matteColor}
                toneMapped={false}
              />
            </mesh>
            <mesh raycast={() => null}>
              <planeGeometry args={[iw, ih]} />
              <meshBasicMaterial map={textures[frame.id]} toneMapped={false} />
            </mesh>
            <mesh
              position={[0, 0, 0.04]}
              onPointerOver={() => setHoveredFrame(frame.id)}
              onPointerOut={() => setHoveredFrame(null)}
              onClick={() => handleClick(frame)}
            >
              <planeGeometry args={PANEL.click} />
              <meshBasicMaterial
                transparent
                opacity={hovered ? 0.12 : 0}
                color={"#1aa89c"}
                depthWrite={false}
              />
            </mesh>
          </group>
        );
      })}
    </group>
  );
}
