// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 DetailT.glb --transform -d
// Files: DetailT.glb [2.58MB] > C:\Users\andre\Downloads\DetailT-transformed.glb [2.51MB] (3%)
// */

import { useEffect, useState } from "react";

import * as THREE from "three";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";

import { convertMaterialsToMeshBasicMaterial } from "../utils/convertMaterial";
import { useModalStore } from "../stores/modalStore";

import About from "../../components/About/About";
import Project from "../../components/Project/Project";
import UserManual from "../../components/UserManual/UserManual";
import RandomLinks from "../../components/RandomLinks/RandomLinks";
import Bookshelf from "../../components/Bookshelf/Bookshelf";

// The four clickable frames on the About wall. The single baked
// About_Me_Pictures mesh stays as the visual; these invisible planes sit over
// each painted frame and open their own modal.
// NOTE(anu): tune `aboutZoneLayout` against the running dev server until the
// planes line up with the four frames on the wall (scroll to the about view).
const aboutFrames = {
  about: { title: "About me", render: () => <About /> },
  manual: { title: "User Manual", render: () => <UserManual /> },
  links: { title: "Random Links", render: () => <RandomLinks /> },
  books: { title: "Currently Reading", render: () => <Bookshelf /> },
};

// Derived from the About_Me_Pictures geometry bounds (worldX[-9.19,-7.14],
// worldY~68.04, worldZ~4.41): four evenly spaced frames ~0.51 wide. The anchor
// sits at the picture centre, nudged slightly toward the camera (smaller z) so
// the invisible planes catch clicks just in front of the painted frames.
const aboutZoneLayout = {
  position: [-8.164, 68.035, 4.3],
  // each plane's local x offset along the wall (left -> right), plus its size
  zones: [
    { id: "about", x: -0.77 },
    { id: "manual", x: -0.26 },
    { id: "links", x: 0.26 },
    { id: "books", x: 0.77 },
  ],
  width: 0.48,
  height: 0.45,
};

export default function Model({ progress = 0, pulseIntensity = 0, ...props }) {
  const { nodes, materials } = useGLTFWithKTX2("/models/DetailT-v1.glb");
  const [hoveredMesh, setHoveredMesh] = useState(null);
  const { openModal } = useModalStore();

  const projectNames = {
    one: "Multiplayer AI Agent Canvas",
    two: "matrixportfolio",
    three: "coding-monkey",
    four: "AI Native Sims City",
  };

  const handleClick = (elementID) => {
    const frame = aboutFrames[elementID];
    if (frame) {
      openModal(frame.title, frame.render(), elementID);
    } else {
      openModal(
        projectNames[elementID],
        <Project projectID={elementID} />,
        elementID
      );
    }
  };

  const baseMaterial = materials["MergedBake_Baked.010"].clone();

  const brightHoveredMaterial = materials["MergedBake_Baked.010"].clone();
  brightHoveredMaterial.color = new THREE.Color(2.5, 2.5, 2.5);

  const pulsingMaterial = materials["MergedBake_Baked.010"].clone();

  convertMaterialsToMeshBasicMaterial(materials, 0);

  const getMaterial = (elementID, progressRange) => {
    if (hoveredMesh === elementID) return brightHoveredMaterial;

    const [min, max] = progressRange;
    if (progress >= min && progress <= max) {
      const pulseColor = 1 + pulseIntensity * 1.5;
      pulsingMaterial.color.setRGB(pulseColor, pulseColor, pulseColor);
      return pulsingMaterial;
    }
    return baseMaterial;
  };

  useEffect(() => {
    document.body.style.cursor = hoveredMesh ? "pointer" : "auto";
  }, [hoveredMesh]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.detail_Baked.geometry}
        material={materials["MergedBake_Baked.010"]}
        position={[-6.46, 69.669, -1.148]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      {/* Static visual: the baked picture wall. Keeps its pulse cue while the
          about area is in view; interaction is handled by the click-zones. */}
      <mesh
        geometry={nodes.About_Me_Pictures.geometry}
        material={getMaterial("about", [0.55, 0.65])}
        position={[-8.164, 68.036, 4.408]}
        rotation={[Math.PI / 2, 0, 0]}
      />

      {/* Four invisible click-zones, one per frame on the about wall. */}
      <group position={aboutZoneLayout.position}>
        {aboutZoneLayout.zones.map((zone) => (
          <mesh
            key={zone.id}
            position={[zone.x, 0, 0]}
            onPointerOver={() => setHoveredMesh(zone.id)}
            onPointerOut={() => setHoveredMesh(null)}
            onClick={() => handleClick(zone.id)}
          >
            <planeGeometry
              args={[aboutZoneLayout.width, aboutZoneLayout.height]}
            />
            <meshBasicMaterial
              transparent
              opacity={hoveredMesh === zone.id ? 0.18 : 0}
              color={"#1aa89c"}
              side={THREE.DoubleSide}
              depthWrite={false}
            />
          </mesh>
        ))}
      </group>
      <mesh
        geometry={nodes.Project_One.geometry}
        material={getMaterial("one", [0.32, 0.43])}
        position={[-10.528, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("one")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("one");
        }}
      />
      <mesh
        geometry={nodes.Project_Two.geometry}
        material={getMaterial("two", [0.32, 0.43])}
        position={[-9.532, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("two")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("two");
        }}
      />
      <mesh
        geometry={nodes.Project_Three.geometry}
        material={getMaterial("three", [0.32, 0.43])}
        position={[-8.536, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("three")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("three");
        }}
      />
      <mesh
        geometry={nodes.Project_Four.geometry}
        material={getMaterial("four", [0.32, 0.43])}
        position={[-7.541, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("four")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("four");
        }}
      />
      <mesh
        geometry={nodes.about_me_text.geometry}
        material={materials["MergedBake_Baked.010"]}
        position={[-8.524, 68.356, 4.727]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
