// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 DetailT.glb --transform -d
// Files: DetailT.glb [2.58MB] > C:\Users\andre\Downloads\DetailT-transformed.glb [2.51MB] (3%)
// */

import { useEffect, useState } from "react";

import * as THREE from "three";
import { useTexture } from "@react-three/drei";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";

import { convertMaterialsToMeshBasicMaterial } from "../utils/convertMaterial";
import { useModalStore } from "../stores/modalStore";

import About from "../../components/About/About";
import Project from "../../components/Project/Project";
import UserManual from "../../components/UserManual/UserManual";
import RandomLinks from "../../components/RandomLinks/RandomLinks";
import Bookshelf from "../../components/Bookshelf/Bookshelf";

// The four clickable frames on the About wall. The single baked
// About_Me_Pictures mesh stays as the visual; these invisible planes sit over
// each painted frame and open their own modal.
// NOTE(anu): tune `aboutZoneLayout` against the running dev server until the
// planes line up with the four frames on the wall (scroll to the about view).
const aboutFrames = {
  about: { title: "About me", render: () => <About /> },
  manual: { title: "User Manual", render: () => <UserManual /> },
  links: { title: "Random Links", render: () => <RandomLinks /> },
  books: { title: "Currently Reading", render: () => <Bookshelf /> },
};

// Derived from the About_Me_Pictures geometry bounds (worldX[-9.19,-7.14],
// worldY~68.04, worldZ~4.41): four evenly spaced frames ~0.51 wide. The anchor
// sits at the picture centre, nudged slightly toward the camera (smaller z) so
// the invisible planes catch clicks just in front of the painted frames.
const aboutZoneLayout = {
  position: [-8.164, 68.035, 4.3],
  // each plane's local x offset along the wall (left -> right), plus its size
  zones: [
    { id: "about", x: -0.77 },
    { id: "manual", x: -0.26 },
    { id: "links", x: 0.26 },
    { id: "books", x: 0.77 },
  ],
  width: 0.48,
  height: 0.45,
};

// In-code photo overlays for the four About-wall frames, mirroring the project
// frame overlays below. The frame pictures are baked into the About_Me_Pictures
// mesh, so we cover each with a plane showing the chosen image. The planes reuse
// the tuned aboutZoneLayout (same group + per-zone x), nudged toward the camera.
// The about wall faces -z, so each plane is turned to face it (rotation
// [lean, PI, 0]) and its texture is mirrored back to upright (repeat.x = -1).
// Raycasting is disabled so the click-zones underneath still open the modals.
// Keyed by the modal each frame opens.
// NOTE(anu): tune offset/width/height against the dev server (scroll to the
// about view) until each image sits flush over its baked frame photo.
const aboutFrameImages = {
  src: {
    about: "/images/me.webp",
    manual: "/images/about-robot.webp",
    links: "/images/newsletter.webp",
    books: "/images/books.webp",
  },
  // local offset from each frame centre (toward the camera) and the photo size
  offset: [0, 0, -0.02],
  width: 0.44,
  height: 0.42,
  // the desk frames are propped leaning back; tilt the overlay to match so it
  // reads as the frame's picture rather than a flat sticker (radians, top away
  // from the camera). NOTE(anu): nudge against the dev server if over/under.
  lean: 0.15,
};

// Crop a texture to "cover" the given plane aspect: fill the frame edge-to-edge
// with no stretching and no borders, keeping the image centred (the excess on
// the long axis is trimmed). `mirror` flips it horizontally for planes that are
// turned to face the camera from behind (the about wall). This is what makes a
// 4:1 banner or a 16:9 shot sit naturally in a near-square frame.
const applyCoverFit = (texture, planeAspect, { mirror = false } = {}) => {
  const img = texture.image;
  const imgAspect = img && img.height ? img.width / img.height : 1;
  let rx = 1;
  let ry = 1;
  if (imgAspect > planeAspect) {
    rx = planeAspect / imgAspect; // image too wide -> trim left/right
  } else {
    ry = imgAspect / planeAspect; // image too tall -> trim top/bottom
  }
  texture.center.set(0.5, 0.5);
  texture.offset.set(0, 0);
  texture.repeat.set(mirror ? -rx : rx, ry);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.needsUpdate = true;
};

// In-code photo overlays for the four project frames. The frame photos are
// baked into the model texture (and the available Blender source is an older,
// mismatched bake), so we cover each frame's baked picture with a plane showing
// the correct project screenshot from /images. The planes sit just in front of
// the frames on the links wall (z = -4.13, facing +z toward the camera) and
// have raycasting disabled so the frames underneath still handle clicks.
// NOTE(anu): tune size/offset against the dev server (scroll to the links view).
const projectFrameImages = {
  src: {
    one: "/images/agent-canvas.webp",
    two: "/images/matrixportfolio.webp",
    three: "/images/coding-monkey.webp",
    four: "/images/ai-native-city.webp",
  },
  // frame face centres (mirror the Project_* mesh positions below)
  centers: {
    one: [-10.528, 69.422, -4.13],
    two: [-9.532, 69.422, -4.13],
    three: [-8.536, 69.422, -4.13],
    four: [-7.541, 69.422, -4.13],
  },
  // local offset of the photo from the frame centre, plus the photo size
  offset: [0, 0.09, 0.06],
  width: 0.62,
  height: 0.56,
};

export default function Model({ progress = 0, pulseIntensity = 0, ...props }) {
  const { nodes, materials } = useGLTFWithKTX2("/models/DetailT-v1.glb");
  const [hoveredMesh, setHoveredMesh] = useState(null);
  const { openModal } = useModalStore();

  // Correct project screenshots overlaid on the baked frame photos. Tag each as
  // sRGB so the colours match the rest of the (flat-rendered) scene.
  const projectFrameAspect = projectFrameImages.width / projectFrameImages.height;
  const frameTextures = useTexture(projectFrameImages.src, (loaded) => {
    Object.values(loaded).forEach((t) => applyCoverFit(t, projectFrameAspect));
  });

  // Images that ride on the four about-wall frames. Cover-fit so they fill each
  // frame without stretching, and mirror horizontally so they read upright once
  // the planes are turned to face the -z-facing wall (see aboutFrameImages).
  const aboutFrameAspect = aboutFrameImages.width / aboutFrameImages.height;
  const aboutTextures = useTexture(aboutFrameImages.src, (loaded) => {
    Object.values(loaded).forEach((t) =>
      applyCoverFit(t, aboutFrameAspect, { mirror: true })
    );
  });

  const projectNames = {
    one: "Multiplayer AI Agent Canvas",
    two: "matrixportfolio",
    three: "coding-monkey",
    four: "AI Native Sims City",
  };

  const handleClick = (elementID) => {
    const frame = aboutFrames[elementID];
    if (frame) {
      openModal(frame.title, frame.render(), elementID);
    } else {
      openModal(
        projectNames[elementID],
        <Project projectID={elementID} />,
        elementID
      );
    }
  };

  const baseMaterial = materials["MergedBake_Baked.010"].clone();

  const brightHoveredMaterial = materials["MergedBake_Baked.010"].clone();
  brightHoveredMaterial.color = new THREE.Color(2.5, 2.5, 2.5);

  const pulsingMaterial = materials["MergedBake_Baked.010"].clone();

  convertMaterialsToMeshBasicMaterial(materials, 0);

  const getMaterial = (elementID, progressRange) => {
    if (hoveredMesh === elementID) return brightHoveredMaterial;

    const [min, max] = progressRange;
    if (progress >= min && progress <= max) {
      const pulseColor = 1 + pulseIntensity * 1.5;
      pulsingMaterial.color.setRGB(pulseColor, pulseColor, pulseColor);
      return pulsingMaterial;
    }
    return baseMaterial;
  };

  useEffect(() => {
    document.body.style.cursor = hoveredMesh ? "pointer" : "auto";
  }, [hoveredMesh]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.detail_Baked.geometry}
        material={materials["MergedBake_Baked.010"]}
        position={[-6.46, 69.669, -1.148]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      {/* Static visual: the baked picture wall. Keeps its pulse cue while the
          about area is in view; interaction is handled by the click-zones. */}
      <mesh
        geometry={nodes.About_Me_Pictures.geometry}
        material={getMaterial("about", [0.55, 0.65])}
        position={[-8.164, 68.036, 4.408]}
        rotation={[Math.PI / 2, 0, 0]}
      />

      {/* Four invisible click-zones, one per frame on the about wall. */}
      <group position={aboutZoneLayout.position}>
        {aboutZoneLayout.zones.map((zone) => (
          <mesh
            key={zone.id}
            position={[zone.x, 0, 0]}
            onPointerOver={() => setHoveredMesh(zone.id)}
            onPointerOut={() => setHoveredMesh(null)}
            onClick={() => handleClick(zone.id)}
          >
            <planeGeometry
              args={[aboutZoneLayout.width, aboutZoneLayout.height]}
            />
            <meshBasicMaterial
              transparent
              opacity={hoveredMesh === zone.id ? 0.18 : 0}
              color={"#1aa89c"}
              side={THREE.DoubleSide}
              depthWrite={false}
            />
          </mesh>
        ))}

        {/* Chosen pictures overlaid on the baked about-wall frames. Turned to
            face the -z wall; raycast disabled so the click-zones still fire. */}
        {aboutZoneLayout.zones.map((zone) => {
          const [ox, oy, oz] = aboutFrameImages.offset;
          return (
            <mesh
              key={`img-${zone.id}`}
              position={[zone.x + ox, oy, oz]}
              rotation={[aboutFrameImages.lean, Math.PI, 0]}
              raycast={() => null}
            >
              <planeGeometry
                args={[aboutFrameImages.width, aboutFrameImages.height]}
              />
              <meshBasicMaterial
                map={aboutTextures[zone.id]}
                toneMapped={false}
                side={THREE.DoubleSide}
              />
            </mesh>
          );
        })}
      </group>
      <mesh
        geometry={nodes.Project_One.geometry}
        material={getMaterial("one", [0.32, 0.43])}
        position={[-10.528, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("one")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("one");
        }}
      />
      <mesh
        geometry={nodes.Project_Two.geometry}
        material={getMaterial("two", [0.32, 0.43])}
        position={[-9.532, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("two")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("two");
        }}
      />
      <mesh
        geometry={nodes.Project_Three.geometry}
        material={getMaterial("three", [0.32, 0.43])}
        position={[-8.536, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("three")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("three");
        }}
      />
      <mesh
        geometry={nodes.Project_Four.geometry}
        material={getMaterial("four", [0.32, 0.43])}
        position={[-7.541, 69.422, -4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        onPointerOver={() => setHoveredMesh("four")}
        onPointerOut={() => setHoveredMesh(null)}
        onClick={() => {
          handleClick("four");
        }}
      />
      <mesh
        geometry={nodes.about_me_text.geometry}
        material={materials["MergedBake_Baked.010"]}
        position={[-8.524, 68.356, 4.727]}
        rotation={[Math.PI / 2, 0, 0]}
      />

      {/* Correct project screenshots overlaid on the baked frame photos.
          raycast disabled so the frame meshes underneath still receive clicks. */}
      {Object.keys(projectFrameImages.src).map((id) => {
        const [cx, cy, cz] = projectFrameImages.centers[id];
        const [ox, oy, oz] = projectFrameImages.offset;
        return (
          <mesh
            key={id}
            position={[cx + ox, cy + oy, cz + oz]}
            raycast={() => null}
          >
            <planeGeometry
              args={[projectFrameImages.width, projectFrameImages.height]}
            />
            <meshBasicMaterial
              map={frameTextures[id]}
              toneMapped={false}
            />
          </mesh>
        );
      })}
    </group>
  );
}
