/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HouseT_new.glb --transform -d

The model is a three-storey, Kathmandu-style brick house rebuilt in Blender as a
single merged mesh: stacked set-back storeys, tiered overhanging hip roofs, front
balconies, and a rooftop terrace, kept in the Minecraft voxel idiom. Geometry is
baked in world coordinates, so the mesh needs no position or rotation here.
*/


import * as THREE from "three";

import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";
import { convertMaterialsToMeshBasicMaterial } from "../utils/convertMaterial";

// Multiplier applied to the house's baked material colour. The scene is fully
// baked and unlit, so scaling the MeshBasicMaterial colour (which multiplies the
// texture) is the only runtime lever. The atlas is baked from flat emission, so
// it already reads at full brightness; keep this at 1.0 and tune against the dev
// server if the house needs to sit lighter or darker against the surroundings.
const INTERIOR_BRIGHTNESS = 1.0;

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2(
    "/models/HouseT-transformed.glb"
  );
  convertMaterialsToMeshBasicMaterial(materials);
  materials["MergedBake"].color.setScalar(INTERIOR_BRIGHTNESS);

  // Render the house in the opaque queue. Opaque geometry writes depth and lets
  // the GPU early-z reject the exterior shaded through window openings; left
  // transparent it tanks scroll framerate once the SkyShell occluder is gone.
  materials["MergedBake"].transparent = false;

  // The camera travels up the interior atrium, so both faces of every wall and
  // floor must render — the baked atlas reads the same from either side.
  materials["MergedBake"].side = THREE.DoubleSide;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.House.geometry}
        material={materials["MergedBake"]}
      />
    </group>
  );
}
