/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HouseT.glb --transform -d 
Files: HouseT.glb [13.54MB] > C:\Users\andre\My Stuff\Blender Projects\Minecraft Portfolio\Objects\For Use\HouseT-transformed.glb [13.48MB] (1%)
*/


import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";
import { convertMaterialsToMeshBasicMaterial } from "../utils/convertMaterial";

// Multiplier applied to the house's baked material colour to lift the dark
// interior. The scene is fully baked and unlit, so scaling the MeshBasicMaterial
// colour (which multiplies the texture) is the only runtime lever. The house is
// a single merged material, so this brightens interior and exterior together;
// keep it modest so the exterior brick does not blow out. Tune against the dev
// server.
const INTERIOR_BRIGHTNESS = 1.4;

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2(
    "/models/HouseT-transformed.glb"
  );
  convertMaterialsToMeshBasicMaterial(materials);
  materials["MergedBake_Baked.016"].color.setScalar(INTERIOR_BRIGHTNESS);

  // Render the house in the opaque queue (it is alpha-cut for the window panes,
  // not alpha-blended). Opaque geometry writes depth and lets the GPU early-z
  // reject the exterior shaded through the window holes; left transparent it
  // tanks scroll framerate once the SkyShell occluder is gone. alphaTest (0.55,
  // set during conversion) still discards the window panes.
  materials["MergedBake_Baked.016"].transparent = false;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.house_Baked.geometry}
        material={materials["MergedBake_Baked.016"]}
        position={[-4.55, 71.054, 0.595]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
